### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by ulgens**
* PEP8 fixes
* Add Jetbrains config folder to .gitignore
* Explicit and verbose error handling

### CODE REVIEW

**Comment by inconvergent** [comment]
this is my own personal tool. i will not accept prs. also: why would you change the indent style? clearly there has been a conscious choice along the way, since there is an .editorconfig file.

**Comment by ulgens** [comment]
I'm following your works for a while and i'm amazed. When i found your Github repo, i tried to run some of your projects but code was broke, dependencies were missing and code quality was not top notch. I thought i can contribute to them and make these tools usable for other people on internet. Apparently, i was wrong.

This is internet, and your repo is public. At this point, nothing is "personal" but you think different and i have to accept it, because its your repo. I'll continue with my fork.

Reason to change indentation, both in code and in .editorconfig was very obvious, as written in commit message: PEP8, de facto standard for code quality and styling in Python ecosystem.

**Comment by inconvergent** [comment]
The repo is public. that does not mean i want contributions. if there is no contribution guide you should not assume people want contributions, even if it is public. please ASK people before sending PRs. the code is MIT, you are free to use it within the bounds of the MIT license. 

Finally: i am well aware of PEP8. as you saw in the editorconfig i have chosen to NOT use PEP8.

**Comment by ulgens** [comment]
Man, i tried to contribute in your code. It's not a bad thing. Even if you don't want it, a simple "thank you but..." is not that hard. I couldn't know you have no understanding about contribution in open source without sending this PR, sorry. You made me regret my decision. I'm not going to try to make you any favor anymore, i assure you.

**Comment by inconvergent** [comment]
it would have been sufficient to send me a message, or open an issue. like i said: if there are no contribution guidelines, you are better off asking first. simply stepping in from out of the blue and touching every line of the project is not helpful in any way.

**Pull request closed without merging**
